### ISSUE TITLE
Complete foundational data wiki page

### ISSUE THREAD

**Issue by tessam30** [tessam30/2018_Kenya#3]
@deitelberg, please complete the Wiki [Foundational Data](https://github.com/tessam30/2018_Kenya/wiki/Foundational-Data).  I'd recommend including a list of the essential data/shapefiles, where they live, and where they are from. 

- [x] Official project crosswalks (County and constituency at minimum)
- [x] Boundary files - Admin 0 - 3
- [x]  Conservancy areas
- [x]  ASAL boundaries
- [x]  Other things I forgot already 
- [x]  Kenya FTF ZOI version 1.0 and 2.0

**Comment by deitelberg** [comment]
| Data                     | Filename               | Type      | Data Location                              | Source                   | Notes |
|--------------------------|------------------------|-----------|--------------------------------------------|--------------------------|-------|
| County Boundaries (2013) | CountyBoundary2013.shp | Shapefile | Google Drive 7.0 - Data/CountyBoundary2013 | Awaiting info from Teddy |       |
|                          |                        |           |                                            |                          |       |
|                          |                        |           |                                            |                          |       |

**Comment by deitelberg** [comment]
Official project crosswalks are in a Google Sheet. These are all the spellings and alternative names I have found. If you come across additional names, please let me know so we can update the sheet appropriately. 
https://docs.google.com/spreadsheets/d/12gOhFZiJDylthVwjBL2cHV34GhCzdJYxWCDmH8OX-Jc/edit#gid=0

**Comment by deitelberg** [comment]
Data list and County-Constituency Crosswalk have been posted to the [Foundational Data Wiki](https://github.com/tessam30/2018_Kenya/wiki/Foundational-Data)

**Comment by tessam30** [comment]
Looks like this all exists in the shared drive folder. Closing the issue.
