### ISSUE TITLE
Kenya Budget Analysis Wiki

### ISSUE THREAD

**Issue by tessam30** [tessam30/2018_Kenya#4]
@bmccusker  - Assinging you this [Budget Analysis Wiki](https://github.com/tessam30/2018_Kenya/wiki/Kenya-Budget-Analysis-Links) to complete/maintain as you gather budget information.

- [x] Data sources
- [x] Budget explanation  
- [x] Feasibility estimate
- [x] Anything else you deem essential

**Comment by tessam30** [comment]
@bmccusker @kabuchanga - feel free to write a markdown file that summarizes work done to date. Would be good to capture what we have done so when we revisit after winters holidays we are not scratching our heads.

**Comment by bmccusker** [comment]
@tessam30 @kabuchanga Ok. I'll write up the procedure and how to do this without having to use NVivo.

**Comment by bmccusker** [comment]
@tessam30 can you post the spreadsheet for master CBA you sketched out on 11/13 meeting?

**Comment by tessam30** [comment]
@bmccusker  budget dat has been posted [here](https://raw.githubusercontent.com/tessam30/2018_Kenya/master/Budget/KEN_budget_categories_long_2016.csv)

**Comment by tessam30** [comment]
@tessam30 volunteered to check the data using a random sample of rows.

**Comment by tessam30** [comment]
Data validation check routine. Found the following errors and am resolving them.

- [x] Budget numbers for Kakamega 2016 Budget numbers improperly coded

- [x] Agriculture budget types mapped into Youth, Gender and Culture for the following places: Nyeri, Siaya, Tana River, West Pokot, Wajir, Taita Taveta, Trans Nzoia, Tharaka Nithi, Uasin Gishu, Nyamira, Nandi, Narok, Vihigia, Nyandaru, Samburu

- [x] Reviewed a few others and modified. 

- [x] Assigned the following unassigned categories.

![image](https://user-images.githubusercontent.com/5873344/49472926-aeaa5900-f7de-11e8-99f9-1b876115a82a.png)

Final dataset to be uploaded to cloud drive and shared w/ team. May need one more round of spot checks to ensure consistency.

**Comment by tessam30** [comment]
These need to be categorized at some point if possible. @kabuchanga @bmccusker

**Comment by bmccusker** [comment]
Could that have been a sorting error? I checked all those codes carefully. I want to make sure I didn’t miss/perpetuate any errors.

**Comment by tessam30** [comment]
@bmccusker, yes I think they were accidental coding errors. I can pass along the updated spreadsheet tomorrow when back in the office. A few cells were left blank while some others were just coded incorrectly. We should spot check together on Thursday.
