### ISSUE TITLE
Election Data Wrangling

### ISSUE THREAD

**Issue by tessam30** [tessam30/2018_Kenya#7]
@rcp7373 

- [x] download 2013 election results
- [x] calculate roll-ups at the constituency and county levels
- [x] standardize constituency codes + names 
- [x] create 2013 table for election results based on 2017 table provided by tim

**Comment by tessam30** [comment]
Election results found and downloaded. Pdf if [here](https://github.com/tessam30/2018_Kenya/blob/master/KEN_2013_Election_results.pdf).

**Comment by tessam30** [comment]
@rcp7373 - Looks like we are nearly done with the checklist. I have not looked at the .csv you shared in detail. Did you also calculate county level roll-ups for each candidate? Happy to chat when you are back from travels.

**Comment by tessam30** [comment]
Apparently the constituency of Suba and Mbita changed to be Suba North and Suba South in the 2017 electoral data. [Suba](https://en.wikipedia.org/wiki/Suba_District) . [Mbita](https://en.wikipedia.org/wiki/Mbita_Constituency) . 

<img width="379" alt="screen shot 2018-12-14 at 4 08 29 pm" src="https://user-images.githubusercontent.com/5873344/50027514-87ac0e00-ffba-11e8-9181-c72b4cf25302.png">

**Comment by rcp7373** [comment]
I remember seeing that and fixed it for the shape file but apparently not
across the years.

**Comment by tessam30** [comment]
Closing this out as things seem to be in order.
